name: open_tarkov_app
description: OpenTarkovApp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  opt_api:
    path: opt_api
  path_provider: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  extended_image: ^8.1.0

  quiver: ^3.2.1
  dartx: ^1.2.0
  fast_immutable_collections: ^9.1.5
  fpdart: ^1.1.0

  google_fonts: ^6.0.0
#  chinese_font_library: ^1.0.1

  defer_pointer: ^0.0.2

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
